- command: cat {{ansible_ssh_private_key_file}}
  register: ssh_key_output 
- set_fact:
    anaconda_ssh_key: "{{ ssh_key_output.stdout }}"
- template:
    src: grub-kvm.j2
    dest: /var/lib/tftpboot/uefi/grub.cfg-{{ hostvars[item]['ethernet'] }}
  with_items: "{{ groups['kvm'] }}"
