- parted: device=/dev/{{ kvm_image_device }} unit=MiB
  register: image_share_info
- systemd:
    name: libvirtd
    state: stopped
- mount:
    path: /var/lib/libvirt/images
    state: unmounted
  ignore_errors: yes
  retries: 3
- lvol:
    vg: vg_kvm_xfs
    lv: kvm_xfs_db
    state: absent
    force: yes
- lvg:
    vg: vg_kvm_xfs
    state: absent
    force: true
- parted:
    device: "/dev/{{ kvm_image_device }}"
    number: '{{ item.num }}'
    state: absent
  loop: '{{ image_share_info.partitions }}'
- parted:
    device: "/dev/{{ kvm_image_device }}"
    number: 1
    flags: [ lvm ]
    state: present
- lvg:
    vg: vg_kvm_xfs
    pvs: "/dev/{{ kvm_image_device }}1"
    state: present
- lvol:
    vg: vg_kvm_xfs
    lv: kvm_xfs_db
    pvs: "/dev/{{ kvm_image_device }}1"
    size: +100%PVS
    resizefs: yes
- filesystem:
    dev: /dev/vg_kvm_xfs/kvm_xfs_db
    fstype: xfs
- file:
    path: /var/lib/libvirt/images
    state: directory
- mount:
    src: /dev/mapper/vg_kvm_xfs-kvm_xfs_db
    path: /var/lib/libvirt/images
    fstype: xfs
    state: mounted
- systemd:
    name: libvirtd
    state: started
