- hosts: bastionhost
  roles:
  - dns
  - ntp
  - tftp
  - dhcp
  - httpd
  - rsyslog
  - haproxy
  - { role: squid, when: squid_install }
  - { role: nexus, when: ocp_install_type == 'disconnected' }
  - kvm
- hosts: kvm
  gather_facts: no
  roles:
  - kvm
- hosts: bastionhost
  roles:
  - upi
