- name: Install TFTP Server
  yum:
    name:
      - tftp-server
      - tftp
      - xinetd
    state: present
- name: Enable TFTP service on firewalld
  firewalld:
    service: tftp
    permanent: yes
    state: enabled
- name: Create directory for UEFI
  file:
    path: /var/lib/tftpboot/uefi
    state: directory
    mode: '0755'
- name: Create image directory
  file:
    path: /var/lib/tftpboot/images/RHEL-8.1
    state: directory
- name: Get Kernel-Version
  shell: "uname -a | awk '{print $3}'"
  register: kernel_version_output
- set_fact:
    kernel_version: "{{ kernel_version_output.stdout }}"
    rescue_version: "7ca6a81ae90949bd8877dd35c8addf45"
- name: Copy vmlinuz
  copy:
    src: "/boot/vmlinuz-{{ kernel_version }}"
    dest: /var/lib/tftpboot/images/RHEL-8.1/vmlinuz
- name: Copy initramfs
  copy:
    src: "/boot/initramfs-{{ kernel_version }}.img"
    dest: /var/lib/tftpboot/images/RHEL-8.1/initramfs.img
    mode: '644'
- name: Copy vmlinuz-rescue
  copy:
    src: "/boot/vmlinuz-0-rescue-{{ rescue_version }}"
    dest: /var/lib/tftpboot/images/RHEL-8.1/vmlinuz-rescue
- name: Copy initramfs-rescue
  copy:
    src: "/boot/initramfs-0-rescue-{{ rescue_version }}.img"
    dest: /var/lib/tftpboot/images/RHEL-8.1/initramfs-rescue.img
    mode: '644'
- name: Copy UEFI BOOTX64.EFI to TFTP Boot
  copy:
    src: /boot/efi/EFI/BOOT/BOOTX64.EFI
    dest: /var/lib/tftpboot/uefi/BOOTX64.efi
    remote_src: yes
    mode: '755'
- name: Copy UEFI Grubx to TFTP Boot 
  copy:
    src: /boot/efi/EFI/redhat/grubx64.efi
    dest: /var/lib/tftpboot/uefi
    remote_src: yes
    mode: '755'
- name: Create TFTP image directory
  file:
    path: /var/lib/tftpboot/images/RedHat-CoreOS
    state: directory
    mode: '0755'
- name: Enable and start TFTP service
  systemd:
    name: tftp
    state: restarted
    enabled: yes
- name: Enable and start XINETD service
  systemd:
    name: xinetd
    state: restarted
    enabled: yes
